### ISSUE TITLE
Oshi.javaの修正

### ISSUE THREAD

**Issue by Piyopanman** [fAyano/AirNagesen#7]
**6月1日に画像修正**
MVCのM(Model)
↓のクラス図(暫定)をみていい感じにお願いします！
<img width="937" alt="スクリーンショット 2021-06-01 8 53 52" src="https://user-images.githubusercontent.com/66374097/120249862-35a8f100-c2b7-11eb-91f9-d6d59f26f847.png">

**Comment by G19908hm** [comment]
ありがとう！！
了解です。頑張ります！！
